name: school_todo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  dio: ^4.0.6
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  device_info_plus: ^3.2.3
  get_it: ^7.2.0

  logging: ^1.0.2
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.20.0
  firebase_remote_config: ^2.0.13
  firebase_crashlytics: ^2.8.6
  hive: ^2.2.3
  path_provider: ^2.0.11
  flutter_launcher_icons: ^0.10.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  hive_generator: ^1.1.1

  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter_icons:
  image_path_android: "assets/images/todo_app_icon.png"
  image_path_ios: "assets/images/todo_app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/double_ex.svg
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
flutter_intl:
  main_locale: ru_RU
  enabled: true
